name: "Comment on PR"

on:
  workflow_run:
    workflows: ["Markdown Linter 🎳"]
    types:
      - completed

jobs:
  comment:
    name: "Comment on PR"
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.event == 'pull_request' }}

    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        with:
          delete: true
          number: ${{ env.PR_NUMBER }}

      - name: "Download build artifact"
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          name: pr-markdown-lint-report
          run_id: ${{ github.event.workflow_run.id }}
          workflow: pr_linter_markdown.yml

      - name: "Restore preserved ENV"
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: cat pr.env >> "${GITHUB_ENV}"

      - name: Merge reports
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: |
          echo ":boom: Erreurs repérées dans la syntaxe Markdown. @${{ env.GITHUB_AUTHOR }} merci de consulter le rapport du linter  :pray:" > msg_comment.txt
          cat ma*.txt >> msg_comment.txt

      # in case of failure
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          if: ${{ github.event.workflow_run.conclusion == 'failure' }}
          recreate: true
          number: ${{ env.PR_NUMBER }}
          path: msg_comment.txt

      # -- USER INFORMATION --------------------------------------------------
      - name: Comment PR - Fail
        id: pr_comment_bad
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: markdown-lint-report-added.txt

      # - name: Comment PR - Success
      #   id: pr_comment_good
      #   if: success()
      #   uses: mshick/add-pr-comment@v1
      #   with:
      #     message: |
      #       :tada: Le markdown a l'air tout propre !
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     allow-repeats: true
